(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var c="\u00d6vers\u00e4tt",e=this||self;function f(a,m){a=a.split(".");var b=e;a[0]in b||"undefined"==typeof b.execScript||b.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===m?b[d]&&b[d]!==Object.prototype[d]?b=b[d]:b=b[d]={}:b[d]=m}var g=/^[\w+/_-]+[=]{0,2}$/,h=null;function k(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&g.test(a)?a:""}function l(a){return a};var n={0:c,1:"Avbryt",2:"St\u00e4ng",3:function(a){return"Google har \u00f6versatt den h\u00e4r sidan automatiskt till: "+a},4:function(a){return"\u00d6versatt till: "+a},5:"Fel: Servern kunde inte slutf\u00f6ra din beg\u00e4ran. F\u00f6rs\u00f6k igen senare.",6:"L\u00e4s mer",7:function(a){return"Drivs av "+a},8:c,9:"\u00d6vers\u00e4ttning p\u00e5g\u00e5r",10:function(a){return"Vill du \u00f6vers\u00e4tta den h\u00e4r sidan till: "+(a+" med Google \u00d6vers\u00e4tt?")},11:function(a){return"Visa sidan p\u00e5: "+
a},12:"Visa originalet",13:"N\u00e4r inneh\u00e5llet i den h\u00e4r lokala filen skickas till Google f\u00f6r \u00f6vers\u00e4ttning anv\u00e4nds en s\u00e4ker anslutning.",14:"N\u00e4r inneh\u00e5llet p\u00e5 den h\u00e4r s\u00e4kra sidan skickas till Google f\u00f6r \u00f6vers\u00e4ttning anv\u00e4nds en s\u00e4ker anslutning.",15:"N\u00e4r inneh\u00e5llet p\u00e5 den h\u00e4r intran\u00e4tsidan skickas till Google f\u00f6r \u00f6vers\u00e4ttning anv\u00e4nds en s\u00e4ker anslutning.",16:"V\u00e4lj spr\u00e5k",
17:function(a){return"Inaktivera \u00f6vers\u00e4ttning av "+a},18:function(a){return"Inaktivera f\u00f6r: "+a},19:"D\u00f6lj alltid",20:"K\u00e4lltext:",21:"Bidra med en b\u00e4ttre \u00f6vers\u00e4ttning",22:"Bidra",23:"\u00d6vers\u00e4tt alla",24:"\u00c5terst\u00e4ll alla",25:"Avbryt alla",26:"\u00d6vers\u00e4tt avsnitten till mitt spr\u00e5k",27:function(a){return"\u00d6vers\u00e4tt allt till "+a},28:"Visa originalspr\u00e5k",29:"Alternativ",30:"Inaktivera \u00f6vers\u00e4ttning f\u00f6r den h\u00e4r webbplatsen",
31:null,32:"Visa alternativa \u00f6vers\u00e4ttningar",33:"Klicka p\u00e5 orden om du vill visa alternativa \u00f6vers\u00e4ttningar",34:"Anv\u00e4nd",35:"H\u00e5ll ned Skift-tangenten och dra om du vill \u00e4ndra ordning",36:"Klicka om du vill visa alternativa \u00f6vers\u00e4ttningar",37:"Om du vill \u00e4ndra ordning p\u00e5 orden ovan h\u00e5ller du ned Skift-tangenten samtidigt som du klickar p\u00e5 orden och drar runt dem.",38:"Tack f\u00f6r att du bidrar med ditt \u00f6vers\u00e4ttningsf\u00f6rslag till Google Translate.",
39:"Hantera \u00f6vers\u00e4ttning f\u00f6r den h\u00e4r webbplatsen",40:"Klicka p\u00e5 ett ord om du vill visa alternativa \u00f6vers\u00e4ttningar, eller dubbelklicka f\u00f6r att redigera direkt",41:"K\u00e4lltext",42:c,43:c,44:"Din \u00e4ndring har skickats in.",45:"Fel: Webbsidans spr\u00e5k st\u00f6ds inte.",46:"\u00d6vers\u00e4ttningswidget f\u00f6r spr\u00e5kmenyn"};var p;function q(a,m){this.g=m===r?a:""}q.prototype.toString=function(){return this.g+""};var r={};var t=window.google&&google.translate&&google.translate._const;
if(t){var u;a:{for(var v=[],w=[""],x=0;x<w.length;++x){var y=w[x].split(","),z=y[0];if(z){var A=Number(y[1]);if(!(!A||.1<A||0>A)){var B=Number(y[2]),C=new Date,D=1E4*C.getFullYear()+100*(C.getMonth()+1)+C.getDate();!B||B<D||v.push({version:z,ratio:A,h:B})}}}var E=0,F=window.location.href.match(/google\.translate\.element\.random=([\d\.]+)/),G=Number(F&&F[1])||Math.random();for(x=0;x<v.length;++x){var H=v[x];E+=H.ratio;if(1<=E)break;if(G<E){u=H.version;break a}}u="TE_20210224_00"}var I="/element/%s/e/js/element/element_main.js".replace("%s",
u);if("0"==u){var J=" element %s e js element element_main.js".split(" ");J[J.length-1]="main_sv.js";I=J.join("/").replace("%s",u)}if(t._cjlc)t._cjlc(t._pas+t._pah+I);else{var K=t._pas+t._pah+I,L,M="SCRIPT",N=document;M=String(M);"application/xhtml+xml"===N.contentType&&(M=M.toLowerCase());L=N.createElement(M);L.type="text/javascript";L.charset="UTF-8";var O,P;if(void 0===p){var Q=null,R=e.trustedTypes;if(R&&R.createPolicy){try{Q=R.createPolicy("goog#html",{createHTML:l,createScript:l,createScriptURL:l})}catch(a){e.console&&
e.console.error(a.message)}p=Q}else p=Q}var S=(P=p)?P.createScriptURL(K):K;O=new q(S,r);L.src=O instanceof q&&O.constructor===q?O.g:"type_error:TrustedResourceUrl";var T;var U=L.ownerDocument&&L.ownerDocument.defaultView;U&&U!=e?T=k(U.document):(null===h&&(h=k(e.document)),T=h);T&&L.setAttribute("nonce",T);var V=document.getElementsByTagName("head")[0];V||(V=document.body.parentNode.appendChild(document.createElement("head")));V.appendChild(L)}f("google.translate.m",n);f("google.translate.v",u)};}).call(window)
